### ISSUE TITLE
Removing due date

### ISSUE THREAD

**Issue by davesaas** [raksul/go-clickup#31]
The Clickup API docs say you can remove a field during an update by passing a null.  Is there a way to remove the due date using the TaskRequest struct and calling the UpdateTask method.  I've tried using 0 for the due date but that has no effect.

**Comment by a-thug** [comment]
@davesaas 
Thanks for your report!
We will check into the matter.

**Comment by w-haibara** [comment]
@davesaas 
Thanks for pointing that out! Could you please provide a link to where it is mentioned?

**Comment by davesaas** [comment]
@w-haibara Sorry I thought I saw it mentioned in the API docs at some point, but cannot find it now.  Though I do see in the samples when there is no due_date, the API will return a null in that field.  I have tried the api using curl, and when you pass null for due date in a PUT (Update) request, it does remove the date.  https://clickup.com/api/clickupreference/operation/UpdateTask/#tag/Tasks/operation/UpdateTask

**Comment by w-haibara** [comment]
Hi, @davesaas !
I respond to this issue by #36 .

> This is the execution result of the sample code to update and remove the due date of the task whose ID is 376jy0a (ccc is the task name).
```
$ go run example/update-duedate/main.go
Enter clickup taskId: 376jy0a

Get due date of current task
ccc 2022-11-17 04:00:00 +0900 JST

Update due date of the task to 2122/01/02 03:04:05:06
ccc 2122-01-02 04:00:00 +0900 JST

Update the task with empty TaskRequest
ccc 2122-01-02 04:00:00 +0900 JST

Remove task due date with NullDate()
ccc <nil>
```

You can use `clickup.NullDate()` to set `null` for DueDate field.
https://github.com/raksul/go-clickup/blob/18cac46eab8c3327cf55d70b5e3f9092ab7449e3/example/update-duedate/main.go#L40-L42

**Comment by davesaas** [comment]
Thanks @w-haibara, I will give it a try.
