### ISSUE TITLE
JSON Marshalling Issue

### ISSUE THREAD

**Issue by graza-io** [raksul/go-clickup#37]
Hi,

It looks like in many places the property Orderindex is incorrectly typed as an int examples:
https://github.com/raksul/go-clickup/blob/18cac46eab8c3327cf55d70b5e3f9092ab7449e3/clickup/checklists.go#L30 
https://github.com/raksul/go-clickup/blob/18cac46eab8c3327cf55d70b5e3f9092ab7449e3/clickup/checklists.go#L39

This leads to errors such as `json: cannot unmarshal number 2.5 into Go struct field Item.tasks.checklists.items.orderindex of type int (SQLSTATE HV000)` when attempting to obtain data where the orderindex isn't an exact integer.

**Comment by graza-io** [comment]
Also on this the `PercentCompleted` in the `goals.go` file should also be of type `float` not `int` 
https://github.com/raksul/go-clickup/blob/18cac46eab8c3327cf55d70b5e3f9092ab7449e3/clickup/goals.go#L94

**Comment by a-thug** [comment]
@graza-io 
Thanks for your report!
We will check into the matter.

**Comment by graza-io** [comment]
@a-thug hey, just wondering if there's any progress on addressing these?

**Comment by a-thug** [comment]
@graza-io 
We hope to have something done by the end of November.
The type of the following fields might be changed like this
- Orderindex: int -> json.Number
- PercentCompleted: int -> float
- FolderAccess: string -> bool

Is there any problem?

**Comment by graza-io** [comment]
That looks about right.
