### ISSUE TITLE
Implement Create/Update/Delete for UserGroup(s)

### ISSUE THREAD

**Issue by catdevman** [raksul/go-clickup#51]
Want to add terraform resource for UserGroup(s) so we need this to support that first.

[Here](https://github.com/catdevman/terraform-provider-clickup/issues/8) is the corresponding task in the terraform provider for click.

**Comment by rek** [comment]
I would be interested in working on this, if there are no plans in place to do this, i will start on a [PR](https://github.com/raksul/go-clickup/pull/52) for it.
