### ISSUE TITLE
Is there a cli tool using this library?

### ISSUE THREAD

**Issue by gilesw** [raksul/go-clickup#64]
I'm looking to setup our clickup programmatically and do some api automations. I've found this terraform repo using your library:-

https://github.com/catdevman/terraform-provider-clickup/blob/main/internal/provider/provider.go

but it seems to only be limited to pulling in data sources.

And no cli that I've found yet.

**Comment by w-haibara** [comment]
This query allows you to check the usage of the package.
https://github.com/search?q=github.com%2Fraksul%2Fgo-clickup+language%3A%22Go+Module%22&type=code&l=Go+Module
